[build]
builder = "dockerfile"

[deploy]
startCommand = "python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = { TRANSFORMERS_CACHE = "/tmp/transformers_cache", TORCH_HOME = "/tmp/torch_cache" }
